server:
  port: 8083
spring:
  application:
    name: ats-users
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ats-user}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:mi-secret-local-superseguro-worksync-2026-ats-usuarios}
    expiration-minutes: 50

eureka:
  client:
    enabled: false
