services:
  postgres:
    image: postgres:16
    container_name: ats-user-postgres
    environment:
      POSTGRES_DB: ats_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ats_pg_data:/var/lib/postgresql/data

volumes:
  - ats_pg_data: