services:
  postgres:
    image: postgres:16
    container_name: ats-user-postgres
    environment:
      POSTGRES_DB: ats_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ats_user_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ats_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ats-user:
    build: .
    container_name: ats-user-app
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ats_user
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-mi-secret-local-superseguro-worksync-2026-ats-usuarios}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ats_user_pg_data:
